#!/bin/bash

rm -rf build
mkdir build
export CMAKE_BUILD_PARALLEL_LEVEL=5
export MACHINEKIT_HAL_CONFIG_DIR=/tmp/hal/config
export MACHINEKIT_HAL_MANAGED_MODULE_OUTPUT_DIRECTORY=/usr/lib/local/
export MACHINEKIT_HAL_MANAGED_MODULE_DIRECTORY=/usr/lib/local/
export MACHINEKIT_HAL_UNMANAGED_MODULE_DIRECTORY=/usr/lib/local/tmp/hal/lib/unmanaged
export MACHINEKIT_HAL_BIN_DIRECTORY=/usr/bin
export MACHINEKIT_HAL_EXECUTABLE_DIRECTORY=/usr/libexec/

cmake -S . -B ./build
cmake --build ./build
sudo cmake --build ./build --target setuid
cmake --build ./build --target binary_tree_venv
cd /src/build/lib/ || exit 1
ln -s libmkhhal_command.so libhal.so.0
ln -s libmkhunmanaged_hal.so libhalulapi.so.0

sudo rsync -av /src/build/ /artifacts/

########################################
# Other MACHINEKIT build variables that
# may come in handy
########################################

# MACHINEKIT_HAL_INTERFACE_DIRECTORY
# MACHINEKIT_HAL_INTERFACE_FULL_INSTALL_DIRECTORY
# MACHINEKIT_HAL_INTERNAL_EXECUTABLE_DIRECTORY
# MACHINEKIT_HAL_INTERNAL_EXECUTABLE_FULL_INSTALL_DIRECTORY
# MACHINEKIT_HAL_INTERNAL_EXECUTABLE_OUTPUT_DIRECTORY)
# MACHINEKIT_HAL_LIBRARY_DIRECTORY
# MACHINEKIT_HAL_LIBRARY_FULL_INSTALL_DIRECTORY
# MACHINEKIT_HAL_LOCAL_STATE_DIRECTORY
# MACHINEKIT_HAL_LOCAL_STATE_FULL_INSTALL_DIRECTORY
# MACHINEKIT_HAL_LOCAL_STATE_OUTPUT_DIRECTORY)
# MACHINEKIT_HAL_MANAGED_FULL_INSTALL_MODULE_DIRECTORY
# MACHINEKIT_HAL_MANAGED_MODULE_DIRECTORY
# MACHINEKIT_HAL_MANAGED_MODULE_DIRECTORY=/tmp/hal/lib/managed
# MACHINEKIT_HAL_MANAGED_MODULE_OUTPUT_DIRECTORY)
# MACHINEKIT_HAL_MANAGED_MODULE_OUTPUT_DIRECTORY=/tmp/hal/lib/managed/
# MACHINEKIT_HAL_SYSTEM_CONFIG_DIRECTORY
# MACHINEKIT_HAL_SYSTEM_CONFIG_FULL_INSTALL_DIRECTORY
# MACHINEKIT_HAL_SYSTEM_CONFIG_OUTPUT_DIRECTORY)
# MACHINEKIT_HAL_TEST_FULL_INSTALL_DIRECTORY
# MACHINEKIT_HAL_TEST_OUTPUT_DIRECTORY)
# MACHINEKIT_HAL_UNMANAGED_FULL_INSTALL_MODULE_DIRECTORY
